using System;
using UnityEngine;
using UnityEngine.UIElements;
using Unity.Properties;

[UxmlElement]
public partial class AdsButton_2 : Button
{
    private IAdsService _adsService;

    public AdsButton_2()
    {
        this.clicked += OnClick;
        this.resolved += OnResolved;

        Debug.Log("AdsButton_2.Constructor");
    }

    private void OnResolved()
    {
        Debug.Log("AdsButton_2.OnResolved");
    }

    private void OnClick()
    {
        Debug.Log("AdsButton_2.OnClick: AdsService = " + _adsService);
        Debug.Log("AdsButton_2.OnClick: IComponentResolver = " + Resolver);

        if (_adsService != null)
        {
            _adsService.ShowRewarded("placement", (success) => { Debug.Log("ShowRewarded callback: " + success); });
        }
    }
}

// ↓↓↓ THIS CODE SHOULD BE GENERATED BY SOURCE CODE GENERATOR ↓↓↓
public partial class AdsButton_2
{
    private IDataSourceResolver _resolver;
    private event Action resolved;

    [CreateProperty]
    public IDataSourceResolver Resolver
    {
        get => _resolver;
        set { _resolver = value; ResolveDependencies(); }
    }

    private void ResolveDependencies()
    {
        _adsService = _resolver.Resolve<IAdsService>();

        resolved?.Invoke();
    }
}
