using UnityEngine;
using UnityEngine.UIElements;
using System;

public class AdsButton_2 : Button
{
    private IAdsService _adsService;

    public AdsButton_2()
    {
        Debug.Log("AdsButton_2 created using default constructor");
    }

    public AdsButton_2(IAdsService adsService) : base()
    {
        _adsService = adsService;

        Debug.Log("AdsButton_2 created using custom constructor");
        Debug.Log("IAdsService exists: " + (_adsService != null));

        this.clicked += OnClick;
    }

    private void OnClick()
    {
        Debug.Log("AdsButton_2 clicked");

        if (_adsService != null)
        {
            // Placement should be a uxml property
            // But now this button is not used UxmlElement attribute
            _adsService.ShowRewarded("placement", (success) =>
            {
                Debug.Log("ShowRewarded callback: " + success);
            });
        }
    }

    // This is should be generated by the source generator
    // Just for exapmle.
    [Serializable]
    public new class UxmlSerializedData : Button.UxmlSerializedData
    {
        public override object CreateInstance()
        {
            if (ComponentFactory.Instance == null)
            {
                // Fallback to default constructor for UXML deserialization
                return new AdsButton_2();
            }

            return ComponentFactory.Instance.Create<AdsButton_2>();
        }
    }
}
